export const FETCH_DATA = 'FETCH_DATA'

// Test actions
export const TEST_ACTION = 'TEST_ACTION';
export const ACTION_TEST_SUCCESSFUL = 'ACTION_TEST_SUCCESSFUL';
export const ACTION_TEST_FAILED = 'ACTION_TEST_FAILED';
export const ACTION_TESTING = 'ACTION_TESTING';

// UI actions
export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';
export const FETCH_NAV_OPTIONS = 'FETCH_NAV_OPTIONS';

// Session actions
export const SESSION_AUTHENTICATING = 'SESSION_AUTHENTICATING';
export const SESSION_AUTHENTICATED = 'SESSION_AUTHENTICATED';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';


// Textures actions
export const FETCH_TEXTURES = 'FETCH_TEXTURES';
export const TEXTURES_LOADED = 'TEXTURES_LOADED';

export const CREATE_TEXTURE = 'CREATE_TEXTURE';
export const DELETE_TEXTURE = 'DELETE_TEXTURE';
export const UPDATE_TEXTURE = 'UPDATE_TEXTURE';
export const UPDATE_CURRENT_TEXTURE = 'UPDATE_CURRENT_TEXTURE';
export const CLEAR_CURRENT_TEXTURE = 'CLEAR_CURRENT_TEXTURE';

export const ASSIGN_TEXTURE = 'ASSIGN_TEXTURE';
export const UNASSIGN_TEXTURE = 'UNASSIGN_TEXTURE';

export const TEXTURES_LOADING = 'TEXTURES_LOADING';
export const TEXTURE_SAVING = 'TEXTURE_SAVING';
export const TEXTURE_SAVED = 'TEXTURE_SAVED';
export const TEXTURES_LOADING_FAILED = 'TEXTURES_LOADING_FAILED';


// Lookup actions
export const ADD_QUALIFICATION = 'ADD_QUALIFICATION';
export const REMOVE_QUALIFICATION = 'REMOVE_QUALIFICATION';
export const UPDATE_QUALIFICATION = 'UPDATE_QUALIFICATION';
export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_CURRENT_ITEM = 'UPDATE_CURRENT_ITEM';
export const CLEAR_CURRENT_ITEM = 'CLEAR_CURRENT_ITEM';